version: "3"

tasks:
  default:
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./migrations
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  app_run:
    cmds:
      - go run ./cmd/sso/main.go --config ./config/local.yaml